version: "3.5"

services:
  boilerplate:
    container_name: boilerplate
    build: .
    environment:
    - NODE_ENV
    - PROJECT_NAME
    - DEBUG_PORT
    - DATABASE_URI
    - APM_HOST
    - TZ=America/Sao_Paulo
    volumes:
      - ./:/app/
    ports:
      - 6328:6328
      - 6329:6329
    networks:
      - loyall-network
    command: npm run dev
networks:
  loyall-network:
    external:
      name: loyall-network